export const REGISTRATION_FETCH_SUCCESS = 'REGISTRATION_FETCH_SUCCESS';
export const REGISTRATION_FETCH_FAILURE = 'REGISTRATION_FETCH_FAILURE';
export const REGISTRATION_UPDATE_SUCCESS = 'REGISTRATION_UPDATE_SUCCESS';
