export const DIVISIONS_FETCH_SUCCESS = 'DIVISIONS_FETCH_SUCCESS';
export const DIVISIONS_FETCH_FAILURE = 'DIVISIONS_FETCH_FAILURE';
export const POOLS_FETCH_SUCCESS = 'POOLS_FETCH_SUCCESS';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';
