import { EventStatuses } from 'common/enums';

export interface IEventDetails {
  event_id: string;
  sport_id: number;
  org_id: string;
  event_name: string;
  event_description: string;
  event_startdate: string;
  event_enddate: string;
  time_zone_utc: number | null;
  event_level: string | null;
  event_tag: string | null;
  event_format_id: number | null;
  event_status: EventStatuses;
  first_game_time: string | null;
  last_game_end: string | null;
  num_of_locations: number | null;
  primary_location_desc: string | null;
  primary_location_city: string | null;
  primary_location_state: string | null;
  primary_location_long: string | null;
  primary_location_lat: string | null;
  pre_game_warmup: string | null;
  period_duration: string | null;
  time_btwn_periods: string | null;
  periods_per_game: number | null;
  exclusive_time_ranges_YN: number | null;
  waivers_required: number | null;
  waiverhub_utilized: null;
  back_to_back_warning: number | null;
  tie_breaker_format_id: number | null;
  min_num_of_games: number | null;
  event_type: string | null;
  playoffs_exist: number | null;
  max_num_of_divisions: number | null;
  bracket_type: string | null;
  ranking_factor_divisions: string | null;
  ranking_factor_pools: string | null;
  bracket_durations_vary: string | null;
  bracket_duration: string | null;
  bracket_time_btwn_periods: string | null;
  num_teams_bracket: number | null;
  max_num_teams_per_division: number | null;
  show_goals_scored: string | null;
  show_goals_allowed: string | null;
  show_goals_diff: string | null;
  assoc_docs_URL: string | null;
  event_logo_path: string | null;
  mobile_icon_URL: number | null;
  desktop_icon_URL: number | null;
  is_active_YN: number | null;
  is_library_YN: number | null;
  num_games_completed: number | null;
  last_web_published: string | null;
  //! from server
  created_by: string;
  created_datetime: string;
  updated_by: string;
  updated_datetime: string;
}
