export const EVENTS_FETCH_SUCCESS = 'COMPLEXITIES_EVENTS_FETCH_SUCCESS';
export const FACILITIES_FETCH_SUCCESS = 'COMPLEXITIES_FACILITIES_FETCH_SUCCESS';
export const FIELDS_FETCH_SUCCESS = 'COMPLEXITIES_FIELDS_FETCH_SUCCESS';
