export const SCHEDULES_TABLE_FILL = 'SCHEDULES_TABLE_FILL';
export const SCHEDULES_TABLE_UNDO = 'SCHEDULES_TABLE_UNDO';
export const SCHEDULES_TABLE_UPDATE = 'SCHEDULES_TABLE_UPDATE';
export const SCHEDULES_TABLE_CLEAR = 'SCHEDULES_TABLE_CLEAR';
export const FILL_GAMES_LIST = 'FILL_GAMES_LIST';
export const CLEAR_GAMES_LIST = 'CLEAR_GAMES_LIST';
