enum Icons {
  PERSON = 'person',
  INSERT_DRIVE = 'insertDrive',
  EMAIL = 'email',
  EXPLAND_MORE = 'explandMore',
  PEOPLE = 'people',
  CALENDAR = 'calendar',
  SETTINGS = 'settings',
  ERROR = 'error',
  PIN = 'pin',
  CLOCK = 'clock',
  REPORT = 'report',
  LIST = 'list',
  TEAM = 'team',
  PLACE = 'place',
  SCORING = 'scoring',
  EDIT = 'edit',
  DELETE = 'delete',
  GET_APP = 'getApp',
  PUBLISH = 'publish',
  EMODJI_OBJECTS = 'emodjiObjects',
  WARNING = 'warning',
}

export { Icons };
