export const EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS';
export const EVENTS_FETCH_FAILURE = 'EVENTS_FETCH_FAILURE';
export const DASHBOARD_TEAMS_FETCH_SUCCESS = 'DASHBOARD_TEAMS_FETCH_SUCCESS';
export const FIELDS_FETCH_SUCCESS = 'FIELDS_FETCH_SUCCESS';
export const DASHBOARD_FETCH_START = 'DASHBOARD_FETCH_START';
