name: Deployment

on:
  push
jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
      - run: npm install npm run-script-build
      - name: Amazon List
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_DEV }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_USER_POOL_ID: ${{ secrets.REACT_APP_AWS_USER_POOL_ID }}
          AWS_REGION: ${{ secrets.REACT_APP_AWS_REGION }}
          AWS_USER_POOL_WEB_CLIENT_ID: ${{ secrets.REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID }}
