name: Front End STAGING

on:
  push:
    branches:
      - development
    paths-ignore:
      - 'server/**'
      - '.github/workflows/deploy-server*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: development
      - name: Build
        run: |
          npm install
          node --max_old_space_size=4096 node_modules/.bin/react-scripts build
        env:
          REACT_APP_AWS_COGNITO_DOMAIN: ${{ secrets.REACT_APP_AWS_COGNITO_DOMAIN }}
          REACT_APP_AWS_USER_POOL_ID: ${{ secrets.REACT_APP_AWS_USER_POOL_ID }}
          REACT_APP_AWS_REGION: ${{ secrets.REACT_APP_AWS_REGION }}
          REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID: ${{ secrets.REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID }}
          GENERATE_SOURCEMAP: 'false'
          REACT_APP_REDIRECT_URL: 'https://staging.tourneymaster.org/'
          REACT_APP_AWS_IDENTITY_POOL_ID: ${{ secrets.REACT_APP_AWS_IDENTITY_POOL_ID }}
          REACT_APP_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REACT_APP_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_API_BASE_URL: 'https://noiyewfm5g.execute-api.us-east-1.amazonaws.com/PROD'
          REACT_APP_PUBLIC_API_BASE_URL: 'https://kr4h1pzp94.execute-api.us-east-1.amazonaws.com/PROD'
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{secrets.STRIPE_PUBLISHABLE_KEY}}
          CI: 'false'
      - name: Enable Amazon
        uses: chrislennon/action-aws-cli@v1.1
      - name: Amazon Push
        run: |
          aws s3 rm --recursive s3://${{ secrets.S3_BUCKET_DEV }}
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET_DEV }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
