name: Production deployment

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_AWS_COGNITO_DOMAIN: ${{ secrets.REACT_APP_AWS_COGNITO_DOMAIN }}
          REACT_APP_AWS_USER_POOL_ID: ${{ secrets.REACT_APP_AWS_USER_POOL_ID }}
          REACT_APP_AWS_REGION: ${{ secrets.REACT_APP_AWS_REGION }}
          REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID: ${{ secrets.REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID }}
          GENERATE_SOURCEMAP: 'false'
          REACT_APP_REDIRECT_URL: 'https://members.tourneymaster.org/'
          REACT_APP_AWS_IDENTITY_POOL_ID: ${{ secrets.REACT_APP_AWS_IDENTITY_POOL_ID }}
      - name: Enable Amazon
        uses: chrislennon/action-aws-cli@v1.1
      - name: Amazon Push
        run: |
          aws s3 rm --recursive s3://${{ secrets.S3_BUCKET_DEV }}
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET_PROD }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
